### ISSUE TITLE
Postgres image is on a different network

### ISSUE THREAD

**Issue by eleijonmarck** [dencold/pgcli-docker#5]
Usually the postgres instance is not spun up on the default network but a network defined as db.

Is there a command/way to access the network and using the pgcli.

Great product btw

I get the following:
```
$ docker network ls
NETWORK ID          NAME                              DRIVER              SCOPE
1c539db56953        starter_default                   bridge              local


$ docker run -it --link starter_db_1:postgres --rm dencold/pgcli                
docker: Error response from daemon: Cannot link to /starter_db_1, as it does not belong to the default network.
```

This seems to solve it but I am not sure how I should be able to do it
https://stackoverflow.com/a/36489937/3767229

**Comment by dencold** [comment]
hey @eleijonmarck apologies for the long delay responding to you. I haven't been actively developing the pgcli tool lately. Did you ever get a solution to this issue? If so, let me know and I'll see if I can apply it to master. Thanks!

**Comment by eleijonmarck** [comment]
Not able to solve it, I think I worked around it somehow :thinking: . Too long as I do not remember how unfortunately

**Comment by dencold** [comment]
Okay, I'm going to close this. If you remember the workaround, feel free to reach out again.

**Comment by slnt** [comment]
@dencold I was having this issue as well.

```
→ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
c41203851c34        postgres:11.8       "docker-entrypoint.s…"   19 hours ago        Up 19 hours         0.0.0.0:5432->5432/tcp   pg11

→ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
f4e0cb563629        partition_network   bridge              local
```

The image was run using `docker-compose up`.

```yaml
version: '3.5'
services:
    db:
        image: postgres:11.8
        container_name: pg11
        environment:
            ...
        ports:
            - 5432:5432
        networks:
            - backend
networks:
    backend:
        name: partition_network
        driver: bridge
```

I've been trying to connect using:

```
→ docker run -it --link pg11:postgres --rm dencold/pgcli
docker: Error response from daemon: Cannot link to /pg11, as it does not belong to the default network.
```

When I add in the network I get a fresh, new error:

```
→ docker run -it --network partition_network --link pg11:postgres --rm dencold/pgcli
Database URL not provided, please try again.

3 ways to use this container:

1. Directly pass the database url:
   docker run -it --rm dencold/pgcli postgres://DBUSER:DBPASS@DBHOST:DBPORT
2. Pass an environment variable via docker's '-e' argument
   docker run -it --rm -e DB_URL=postgres://DBUSER:DBPASS@DBHOST:DBPORT dencold/pgcli
3. Automatically connect via a linked postgres container (my favorite):
   docker run -it --rm --link YOURCONTAINER:postgres dencold/pgcli
```

**Comment by slnt** [comment]
Following up:

In order to get this to kind of work, although not the same way exactly, I modified my `docker-compose.yml` to:

```
version: '3.5'
services:
    db:
        image: postgres:11.8
        container_name: pg11
        environment:
            ...
        ports:
            - 5432:5432
        network_mode: bridge
```

and was able to successfully link my way to success.
